# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Content', models.TextField(max_length=200)),
                ('Created', models.DateTimeField(verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectText', models.TextField(max_length=200)),
                ('numValue', models.IntegerField(default=0)),
                ('titleTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Post')),
            ],
        ),
    ]
