# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160613_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='titleTitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Content',
        ),
        migrations.DeleteModel(
            name='Select',
        ),
    ]
